Console.WriteLine("Для нахождения координаты точки пересечения, введите коэффиценты: ");
Console.WriteLine("Введите коэфицент k1: ");
double k1 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите коэфицент k2: ");
double k2 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите коэфицент b1: ");
double b1 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите коэфицент b2: ");
double b2 = double.Parse(Console.ReadLine());
double x = (b2 - b1) / (k1 - k2);
double y = k2 * x + b2;
Console.WriteLine("Координаты точки пересечения:("+ x + ";" + y + ")");
